services:
  # Backend API Service
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./backend/src:/app/src
    networks:
      - friendscheduler-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend UI Service
  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "19006:19006"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
      - EXPO_WEB=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=19006
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/assets:/app/assets
      - /app/node_modules
    depends_on:
      api:
        condition: service_healthy
    networks:
      - friendscheduler-network
    stdin_open: true
    tty: true
    command: ["npm", "run", "web"]

networks:
  friendscheduler-network:
    driver: bridge
