[variables]
JAVA_VERSION = "21"

[phases.setup]
nixPkgs = ["openjdk21", "curl"]

[phases.build]
cmd = "cd backend && chmod +x ./gradlew && ./gradlew clean build -x test --no-daemon"

[start]
cmd = "cd backend && java -Dserver.port=$PORT -jar build/libs/demo-0.0.1-SNAPSHOT.jar"