[variables]
JAVA_VERSION = "21"

[phases.setup]
nixPkgs = ["openjdk21", "curl"]

[phases.build]
cmd = """
ls -la
ls -la gradle/wrapper/ || echo "No gradle wrapper found"
chmod +x ./gradlew || echo "gradlew not found"
ls -la ./gradlew || echo "gradlew file missing"
./gradlew --version
./gradlew clean build -x test --no-daemon --stacktrace
ls -la build/libs/
"""

[start]
cmd = "java -jar build/libs/friendscheduler-0.0.1-SNAPSHOT.jar"